# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Users/dell/Vivado/ModelTest_v2/ModelTest_v2.srcs/sources_1/ip/blk_mem_increase_buf/blk_mem_increase_buf.xci
# IP: The module: 'blk_mem_increase_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Users/dell/Vivado/ModelTest_v2/ModelTest_v2.srcs/sources_1/ip/blk_mem_increase_buf/blk_mem_increase_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_increase_buf'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Users/dell/Vivado/ModelTest_v2/ModelTest_v2.srcs/sources_1/ip/blk_mem_increase_buf/blk_mem_increase_buf.xci
# IP: The module: 'blk_mem_increase_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Users/dell/Vivado/ModelTest_v2/ModelTest_v2.srcs/sources_1/ip/blk_mem_increase_buf/blk_mem_increase_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_increase_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
